# Generated by Django 6.0.7 on 2026-07-20 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0002_alter_institution_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Chairman', 'Chairman'), ('Administrator', 'Administrator'), ('Principal', 'Principal'), ('Accountant', 'Accountant'), ('Office Staff', 'Office Staff'), ('Faculty', 'Faculty'), ('Librarian', 'Librarian')], max_length=30)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
