# Generated by Django 6.0.7 on 2026-07-20 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission_no', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('dob', models.DateField()),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('aadhaar', models.CharField(blank=True, max_length=20)),
                ('admission_type', models.CharField(choices=[('PUC', 'PUC'), ('Diploma', 'Diploma Lateral Entry')], max_length=20)),
                ('status', models.CharField(choices=[('Applicant', 'Applicant'), ('Admitted', 'Admitted'), ('Active', 'Active'), ('Internship', 'Internship'), ('Completed', 'Completed'), ('Discontinued', 'Discontinued'), ('Transfer', 'Transfer'), ('Alumni', 'Alumni')], default='Applicant', max_length=20)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='AcademicYear',
        ),
        migrations.RemoveField(
            model_name='department',
            name='institution',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
