# Generated by Django 6.0.7 on 2026-07-20 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_delete_academicyear_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('father_name', models.CharField(max_length=200)),
                ('father_mobile', models.CharField(blank=True, max_length=15)),
                ('father_occupation', models.CharField(blank=True, max_length=100)),
                ('father_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mother_name', models.CharField(max_length=200)),
                ('mother_mobile', models.CharField(blank=True, max_length=15)),
                ('mother_occupation', models.CharField(blank=True, max_length=100)),
                ('guardian_name', models.CharField(blank=True, max_length=200)),
                ('guardian_mobile', models.CharField(blank=True, max_length=15)),
                ('relationship', models.CharField(blank=True, max_length=50)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='students.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
