# Generated by Django 6.0.7 on 2026-07-21 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_academicyear_department_course'),
        ('students', '0003_studentparent'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAcademic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('semester', models.PositiveSmallIntegerField(default=1)),
                ('batch', models.CharField(blank=True, max_length=30)),
                ('roll_number', models.CharField(blank=True, max_length=30)),
                ('admission_date', models.DateField()),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.academicyear')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.department')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic', to='students.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
